### ISSUE TITLE
The plugin does not connect to the bot.

### ISSUE THREAD

**Issue by mrdkind** [soberhacker/obsidian-telegram-sync#284]
After March 29, the plugin remains in connecting mode and does not connect to the Telegram bot. I tried with some bots and some of my friends also had this problem

**Comment by mrdkind** [comment]
iran

**Comment by MooWantFree** [comment]
I encountered the same problem, because the country where I live has blocked the network connection of Telegram. Therefore, my current practice is to replace all the fixed Telegram URLs in the plugins or use a network proxy. I was wondering, could the plugin itself provide a place to customize the bot URL?

**Comment by soberhacker** [comment]
> I encountered the same problem, because the country where I live has blocked the network connection of Telegram. Therefore, my current practice is to replace all the fixed Telegram URLs in the plugins or use a network proxy. I was wondering, could the plugin itself provide a place to customize the bot URL?

@MooWantFree Hmm, very interesting. So, you manually edit main.js, yes? Which strings are you replacing and with what?

**Comment by soberhacker** [comment]
@mrdkind Аre you still having problems with connection?

**Comment by MooWantFree** [comment]
@soberhacker I built a ws proxy and http proxy on my server, and replace the url which in devTools-network to my proxy url
