### ISSUE TITLE
Can't turn it on

### ISSUE THREAD

**Issue by chloe5685** [soberhacker/obsidian-telegram-sync#60]

**Comment by chloe5685** [comment]
I installed it on my Android cellphone, but I can't turn it on

**Comment by soberhacker** [comment]
Hi! Thank you for your feedback. My plugin hasn’t been approved yet, so it will be in the plugin community in a few days.

Also this plugin is only for Linux, MacOS, Windows, because Obsidian doesn't support external libraries on mobile platforms. And I used such one for connectiong to Telegram bots. 
I marked my plugin "isDesktopOnly" in manifest.json. The workflow is next: you send your data to your Telegram bot. When you open Obsidian on your laptop (etc) it will sync everythink. It syncs not only when Obsidian Desktop starts but also during all time Obsidian is opened. For syncing your notes and files between different devices you should use Obsidian Sync, Syncthing, ICloud, Google Drive, etc. 
If you use Obsidian only on your cellphone, you can create your notes directly in Obsidian, or use "share" to transfer data between mobile applications.

f you have any further questions, please contact us. Have a good day!
